import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import Navbar from '@/components/Navbar/Navbar'
import SignInModal from '@/components/Modals/SignInModal/SignInModal'
import SignUpModal from '@/components/Modals/SignUpModal/SignUpModal'
import { ModalProvider } from '@/context/modalContext'
import UserProvider from '@/context/UserContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Giorgi Machitadze - The Maze',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <ModalProvider>
        <UserProvider>
          <SignInModal />
          <SignUpModal />
        
          <Navbar />
          {children}
        </UserProvider>
        </ModalProvider>
        
      </body>
    </html>
  )
}
